import { Product } from '../types';

const BASE_PRODUCTS: Product[] = [
  // ==========================================
  // 1. STANDARD CELEBRATION CAKES (15 Products)
  // ==========================================
  {
    id: "belgian-chocolate-truffle",
    name: "Belgian Chocolate Truffle",
    description: "Rich Belgian chocolate ganache layered between moist cocoa sponge. Our absolute bestseller in Delhi NCR.",
    price: 850,
    categories: ["Cakes"],
    occasions: ["Birthday", "Anniversary"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    weights: [0.5, 1, 1.5, 2]
  },
  {
    id: "red-velvet-romance",
    name: "Red Velvet Cheese Frosting",
    description: "Traditional vibrant red velvet layers with rich whipped cream cheese. Super silky, certified eggless texture.",
    price: 950,
    categories: ["Cakes"],
    occasions: ["Wedding", "Anniversary"],
    flavors: ["Red Velvet"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    weights: [0.5, 1, 2]
  },
  {
    id: "premium-butterscotch",
    name: "Premium Butterscotch Crunch",
    description: "Classic golden honey sponge layered with butterscotch cream and crunchy caramelized praline cashews.",
    price: 750,
    categories: ["Cakes"],
    occasions: ["Birthday"],
    flavors: ["Butterscotch"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    weights: [0.5, 1, 1.5]
  },
  {
    id: "strawberry-fields",
    name: "Starlight Strawberry Fields",
    description: "Fresh orchard-picked strawberries with smooth vanilla bean cream on fluffy sponge layers.",
    price: 800,
    categories: ["Cakes"],
    occasions: ["Festival", "Birthday"],
    flavors: ["Strawberry"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    weights: [0.5, 1, 2]
  },
  {
    id: "pineapple-paradise",
    name: "Pineapple Paradise Cake",
    description: "Sweet, tangy caramelized pineapple chunks folded within chilled premium dairy cream and juicy sponge.",
    price: 699,
    categories: ["Cakes"],
    occasions: ["Birthday", "Festival"],
    flavors: ["Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    weights: [0.5, 1]
  },
  {
    id: "blueberry-bliss",
    name: "Blueberry Bliss Cake",
    description: "Imported wild blueberry compote layered beautifully with rich mascarpone and soft vanilla cream.",
    price: 899,
    categories: ["Cakes"],
    occasions: ["Anniversary", "Birthday"],
    flavors: ["Blueberry"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    weights: [0.5, 1, 1.5]
  },
  {
    id: "black-forest-traditional",
    name: "Black Forest Traditional",
    description: "Rich dark chocolate shaving flakes, sweet glazed cherries, and fresh double-whipped vanilla dairy cream.",
    price: 799,
    categories: ["Cakes"],
    occasions: ["Birthday"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    weights: [0.5, 1, 2]
  },
  {
    id: "chocolate-hazelnut",
    name: "Chocolate Hazelnut Premium",
    description: "Roasted hazelnuts mixed into a dense Nutella cream paste layered with luxury French cocoa sponge.",
    price: 1100,
    categories: ["Cakes"],
    occasions: ["Anniversary", "Birthday"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    weights: [0.5, 1, 1.5, 2]
  },
  {
    id: "mango-cream",
    name: "Majestic Mango Cream",
    description: "Seasonal sweet Alphonso pulp whipped into light yellow dairy cream frosting. A pure premium delight.",
    price: 850,
    categories: ["Cakes"],
    occasions: ["Birthday", "Festival"],
    flavors: ["Mixed"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    weights: [0.5, 1]
  },
  {
    id: "bento-mini-choco",
    name: "Bento Chocolate Mini",
    description: "The viral Korean lunchbox cake. Sized for 1-2 people, packaged in a biodegradable container with a candle.",
    price: 499,
    categories: ["Cakes"],
    occasions: ["Birthday", "Kids Special"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    isNew: true,
    weights: [0.25]
  },
  {
    id: "fresh-fruit-gateau",
    name: "Orchard Fresh Fruit Gateau",
    description: "Moist vanilla layers covered with rich custard cream and crowned with freshly cut kiwi, apple, grapes and orange.",
    price: 899,
    categories: ["Cakes"],
    occasions: ["Birthday", "Festival"],
    flavors: ["Mixed"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    weights: [0.5, 1, 2]
  },
  {
    id: "white-chocolate-raspberry",
    name: "White Chocolate Raspberry Royale",
    description: "Velvety white chocolate mousse with wild pink raspberry compote layers and delicate white chocolate curls.",
    price: 1050,
    categories: ["Cakes"],
    occasions: ["Anniversary", "Wedding"],
    flavors: ["Strawberry"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    weights: [0.5, 1, 1.5]
  },
  {
    id: "caramel-macchiato-cake",
    name: "Gourmet Caramel Macchiato Cake",
    description: "Infused with organic espresso syrup, layered with smooth caramel milk mousse and salted butter drizzle.",
    price: 900,
    categories: ["Cakes"],
    occasions: ["Birthday", "Anniversary"],
    flavors: ["Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1511018556340-d16986a1c194?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isNew: true,
    weights: [0.5, 1, 1.5]
  },
  {
    id: "oreo-cookies-cream",
    name: "Ultimate Oreo Cookies & Cream",
    description: "Crunchy Oreo biscuit crumbles folded into double cream vanilla frosting piled on chocolate chiffon layers.",
    price: 850,
    categories: ["Cakes"],
    occasions: ["Kids Special", "Birthday"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    weights: [0.5, 1, 2]
  },
  {
    id: "pistachio-saffron-kundan",
    name: "Royal Pistachio Saffron Rose Cake",
    description: "Gourmet cardamom-infused sponge soaked in rich Saffron badam milk, finished with roasted Iranian pistachios.",
    price: 1250,
    categories: ["Cakes"],
    occasions: ["Festival", "Wedding"],
    flavors: ["Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1512414589043-f11bfa6e54b8?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    weights: [1, 2]
  },

  // ==========================================
  // 2. DESIGNER & CUSTOM THEME CAKES (15 Products)
  // ==========================================
  {
    id: "wedding-tier-lux",
    name: "Luxurious Wedding Tier",
    description: "Bespoke multi-tiered wedding centerpiece finished with 24K edible gold foil and sugar roses.",
    price: 4500,
    categories: ["Custom Cakes"],
    occasions: ["Wedding", "Anniversary"],
    flavors: ["Vanilla", "Strawberry"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1513135065346-a098a63a71ee?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    weights: [3, 5]
  },
  {
    id: "cosmos-galaxy",
    name: "Cosmos Galaxy Star Cake",
    description: "Deep celestial hand-painted purple & navy buttercream cake topped with chocolate asteroid dust.",
    price: 2800,
    categories: ["Custom Cakes"],
    occasions: ["Birthday", "Kids Special"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1516685018646-549198525c1b?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    weights: [1, 2, 3]
  },
  {
    id: "unicorn-pastel",
    name: "Unicorn Pastel Smash",
    description: "Cute dreamy unicorn containing a colorful chocolate interior and exquisite hand-piped pastel rainbow hair swirls.",
    price: 2200,
    categories: ["Custom Cakes"],
    occasions: ["Birthday", "Kids Special"],
    flavors: ["Strawberry", "Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1614707267537-b85acf00c4b8?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    weights: [1.5, 2]
  },
  {
    id: "under-sea-mermaid",
    name: "Under The Sea Mermaid",
    description: "Finished with custom edible chocolate mermaid tails, pastel shells, sea corals, and teal frosting ocean waves.",
    price: 3200,
    categories: ["Custom Cakes"],
    occasions: ["Birthday", "Kids Special"],
    flavors: ["Blueberry", "Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1535141123063-02f50b93a303?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    weights: [1.5, 2, 3]
  },
  {
    id: "royal-gold-leaf",
    name: "Royal Gold Leaf Crown",
    description: "Ultra-luxury design featuring a rich charcoal black buttercream backdrop, chocolate crown and 24K gold foil.",
    price: 3500,
    categories: ["Custom Cakes"],
    occasions: ["Birthday", "Anniversary"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1527489377706-5bf97e608852?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    weights: [2, 3]
  },
  {
    id: "rose-bouquet-bespoke",
    name: "Bespoke Rose Bouquet",
    description: "Detailed handcrafted individual buttercream cream roses hand-piped gracefully on vanilla velvet cake.",
    price: 2900,
    categories: ["Custom Cakes"],
    occasions: ["Anniversary", "Wedding"],
    flavors: ["Red Velvet", "Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1530187573043-fd91517f7f3d?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    weights: [1.5, 2]
  },
  {
    id: "superhero-avengers",
    name: "Superhero Avengers Theme Cake",
    description: "Double tier kids special containing hand-molded edible sugar crests of Iron Man, Captain America, and Thor.",
    price: 3600,
    categories: ["Custom Cakes"],
    occasions: ["Birthday", "Kids Special"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1574085733277-851d9d856a3a?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isNew: true,
    weights: [2, 3]
  },
  {
    id: "retro-comic-pop",
    name: "Retro Comic Book Pop Cake",
    description: "Stunning cartoon 2D comic strip stenciled cake with dramatic hand-drawn black outlines. Perfect for gen-z.",
    price: 2700,
    categories: ["Custom Cakes"],
    occasions: ["Birthday"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1551879400-111aef497cf4?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    weights: [1, 2]
  },
  {
    id: "little-princess-tiara",
    name: "Royal Princess Tiara Cake",
    description: "Blush pink fondant base wrapped in elegant white pearls and topped with a glistening, edible golden tiara crown.",
    price: 3100,
    categories: ["Custom Cakes"],
    occasions: ["Birthday", "Kids Special"],
    flavors: ["Vanilla", "Strawberry"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1548364538-60b952c308b9?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    weights: [1.5, 2]
  },
  {
    id: "soccer-field-goal",
    name: "Champ Soccer Field Match",
    description: "Green velvet textured football pitch with edible chocolate players, dual custom goal nets and soccer ball topper.",
    price: 2800,
    categories: ["Custom Cakes"],
    occasions: ["Birthday", "Kids Special"],
    flavors: ["Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1505976378723-9726af549e4a?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    weights: [1.5, 2]
  },
  {
    id: "makeup-glamour-box",
    name: "Glow Makeup Glamour Box",
    description: "Exquisite cosmetics customized theme cake featuring hand-drawn sugar lipsticks, eye shadow pallets, and hair brushes.",
    price: 3400,
    categories: ["Custom Cakes"],
    occasions: ["Birthday", "Anniversary"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1490138139357-fc970367727e?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    weights: [1.5, 2]
  },
  {
    id: "jungle-safari-child",
    name: "Wild Jungle Safari Birthday",
    description: "Friendly hand-crafted sugar lions, monkeys, and giraffes nestled within cute giant green leaves and pastel logs.",
    price: 3500,
    categories: ["Custom Cakes"],
    occasions: ["Birthday", "Kids Special"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1512414589043-f11bfa6e54b8?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    weights: [2, 3]
  },
  {
    id: "gym-dumbbell-lift",
    name: "Heavyweight Gym Dumbbell Cake",
    description: "Realistic look-alike sports gym themed black dumbbell cake with barbell weights, protein shake replica.",
    price: 2900,
    categories: ["Custom Cakes"],
    occasions: ["Birthday"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1518047601542-79f18c655718?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    weights: [1.5, 2]
  },
  {
    id: "racing-sports-car",
    name: "Monaco Red Racing Car",
    description: "Fully 3D sculpted edible sports car cake with glistening sugar windshield, rubber chocolate wheels and racing numbers.",
    price: 3900,
    categories: ["Custom Cakes"],
    occasions: ["Birthday", "Kids Special"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    weights: [2, 3]
  },
  {
    id: "pastel-anniversary-slate",
    name: "Aesthetic Pastel Anniversary Ring",
    description: "Chic modern heart design cake decorated with dynamic pastel colors, gold-lined edges and customizable direct calligraphy.",
    price: 2400,
    categories: ["Custom Cakes"],
    occasions: ["Anniversary", "Wedding"],
    flavors: ["Red Velvet"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1562266563-fa44c266111d?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    weights: [1, 1.5, 2]
  },

  // ==========================================
  // 3. SPECIALTY PASTRIES & SLICES (12 Products)
  // ==========================================
  {
    id: "blueberry-cheesecake-slice",
    name: "Blueberry Cheesecake Slice",
    description: "Decadent cream cheese bakedニューヨーク style layered with fresh sweet blueberry preservation glaze.",
    price: 199,
    categories: ["Pastries"],
    occasions: ["Birthday"],
    flavors: ["Blueberry"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1524351199679-46cddf530c04?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isBestseller: true
  },
  {
    id: "pastry-box-mini",
    name: "Mini Pastry Box (6 Pcs)",
    description: "A luxury curation of our single slices: Chocolate Truffle, Velvet Rose, and Vanilla Cream Fruits.",
    price: 599,
    categories: ["Pastries"],
    occasions: ["Festival", "Birthday"],
    flavors: ["Mixed"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isBestseller: true,
    isNew: true
  },
  {
    id: "midnight-truffle-slice",
    name: "Midnight Chocolate Truffle Slice",
    description: "Deep premium dark chocolate fudge pastry layered with high cocoa-butter solids and ganache glaze.",
    price: 140,
    categories: ["Pastries"],
    occasions: ["Birthday"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },
  {
    id: "mango-custard-velvet-slice",
    name: "Mango Custard Velvet Slice",
    description: "Delicate sponge slice topped with light diplomat mango cream and glazed Alphonso mango slices.",
    price: 160,
    categories: ["Pastries"],
    occasions: ["Festival"],
    flavors: ["Mixed"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isNew: true
  },
  {
    id: "espresso-tiramisu-slice",
    name: "Classic Espresso Tiramisu Slice",
    description: "Traditional Italian treat layered with espresso-soaked ladyfinger cookies, smooth whipped mascarpone & dark cocoa.",
    price: 220,
    categories: ["Pastries"],
    occasions: ["Anniversary"],
    flavors: ["Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1571877227200-a0d98ea607e6?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isBestseller: true
  },
  {
    id: "red-velvet-cheese-slice",
    name: "Crimson Red Velvet Cheese Slice",
    description: "Individually sliced cocoa vanilla buttermilk pastry with real dairy cream cheese cloud piping.",
    price: 180,
    categories: ["Pastries"],
    occasions: ["Birthday"],
    flavors: ["Red Velvet"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1616031037011-08bc3e4130d2?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },
  {
    id: "lemon-meringue-slice",
    name: "Zesty Lemon Meringue Tartlet",
    description: "Shortbread crust loaded with rich organic lemon curd and finished with lightly roasted egg-free sweet meringue peaks.",
    price: 150,
    categories: ["Pastries"],
    occasions: ["Festival"],
    flavors: ["Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1551462147-ff29053bfc14?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },
  {
    id: "premium-hazelnut-slice",
    name: "Gourmet Hazelnut Crunch Slice",
    description: "French opera styling with dense layers of hazelnut wafer paste, dark chocolate, and cocoa biscuit.",
    price: 199,
    categories: ["Pastries"],
    occasions: ["Anniversary"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1606312619070-d48b4c652a52?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isBestseller: true
  },
  {
    id: "belgian-choco-eclair",
    name: "Belgian Chocolate Éclair",
    description: "Golden choux pastry stuffed with chilled rich vanilla bean custard and dipped in warm Belgian dark ganache.",
    price: 140,
    categories: ["Pastries"],
    occasions: ["Kids Special"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },
  {
    id: "strawberry-pistachio-tartlet",
    name: "Strawberry Pistachio Custard Tart",
    description: "Crispy sweet pastry cup filled with rich vanilla bean cream, topped with fresh strawberry halves and crushed pistachio.",
    price: 175,
    categories: ["Pastries"],
    occasions: ["Festival"],
    flavors: ["Strawberry"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1515467873230-07bfcf5c7a52?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isNew: true
  },
  {
    id: "opera-coffee-pastry-classic",
    name: "Classic Parisian Opera Pastry",
    description: "Six elegant layers of almond sponge cake soaked in coffee syrup, layered with dark chocolate ganache and espresso cream.",
    price: 240,
    categories: ["Pastries"],
    occasions: ["Anniversary"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1508737804141-4c3b688e25ba?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },
  {
    id: "rose-milk-tres-leches",
    name: "Pistachio Rose Tres Leches",
    description: "Soft vanilla cake soaked completely in sweet milk cream infused with edible rose syrup and crushed almonds.",
    price: 210,
    categories: ["Pastries"],
    occasions: ["Festival"],
    flavors: ["Mixed"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1541746972996-4e0b0f43e01a?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },

  // ==========================================
  // 4. CUPCAKES, BROWNIES & DESSERTS (10 Products)
  // ==========================================
  {
    id: "classic-brownie-fudgy",
    name: "Classic Fudgy Brownie",
    description: "Densely baked Belgian melted chocolate brownie containing toasted walnuts and glossy chocolate fudge.",
    price: 120,
    categories: ["Brownies", "Desserts"],
    occasions: ["Birthday"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1564355808539-22fda35bed7e?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isBestseller: true
  },
  {
    id: "gold-rocher-cupcake",
    name: "Gold Rocher Cupcake",
    description: "Chocochip cupcake topped with silky Nutella buttercream and a luxury Ferrero chocolate crown.",
    price: 150,
    categories: ["Cupcakes", "Desserts"],
    occasions: ["Birthday", "Kids Special"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isBestseller: false
  },
  {
    id: "warm-nutella-lava",
    name: "Warm Nutella Lava Cake",
    description: "Decadently moist cocoa pod featuring warm running hazelnut center. Microwave 15 seconds before eating.",
    price: 180,
    categories: ["Desserts"],
    occasions: ["Anniversary"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1511911063855-2bf39afa5b2e?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isNew: true
  },
  {
    id: "velvet-cream-cupcakes",
    name: "Velvet Cream Cupcake Pack (4 Pcs)",
    description: "A gorgeous set of 4 cupcakes topped with cream cheese piping and colorful sprinkles.",
    price: 299,
    categories: ["Cupcakes", "Desserts"],
    occasions: ["Birthday", "Festival"],
    flavors: ["Red Velvet", "Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isBestseller: true
  },
  {
    id: "walnut-choco-muffin",
    name: "Rich Walnut Chocochip Muffin",
    description: "Soft, golden baked vanilla muffin topped with organic walnuts, dark chocochips, and sweet honey drizzle.",
    price: 95,
    categories: ["Cupcakes"],
    occasions: ["All"],
    flavors: ["Mixed"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1548364538-60b952c308b9?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },
  {
    id: "speculoos-jar-cake-lux",
    name: "Caramelized Speculoos Jar Cake",
    description: "Compact reusable glass jar containing rich lotus biscuit spread, whipped white mousse, and cookie cookies.",
    price: 199,
    categories: ["Desserts"],
    occasions: ["Birthday", "Festival"],
    flavors: ["Butterscotch"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isNew: true
  },
  {
    id: "overloaded-choco-jar",
    name: "Overloaded Chocolate Jar Cake",
    description: "Double layers of moist chocolate truffle sponge and warm running fudge syrup, layered inside a pretty jar.",
    price: 185,
    categories: ["Desserts"],
    occasions: ["Birthday", "Kids Special"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },
  {
    id: "red-velvet-dream-jar",
    name: "Red Velvet Dream Jar Cake",
    description: "Cream cheese mouse layers interspaced with soft scarlet crumbs and vanilla syrup inside our custom glass jar.",
    price: 195,
    categories: ["Desserts"],
    occasions: ["Anniversary", "Birthday"],
    flavors: ["Red Velvet"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },
  {
    id: "assorted-macarons-12",
    name: "Assorted French Macarons (12 Pcs)",
    description: "Premium French treat box containing crisp almond flour cookies filled with strawberry, chocolate, lemon, and pistachio ganache.",
    price: 699,
    categories: ["Desserts"],
    occasions: ["Festival", "Anniversary"],
    flavors: ["Mixed"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1559622214-f8a98509db7b?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isBestseller: true
  },
  {
    id: "fudge-smores-brownie",
    name: "Hot Fudge S'mores Brownie",
    description: "Warm fudgy chocolate base baked with fire-toasted sweet vegetarian marshmallows and graham cracker crumble.",
    price: 160,
    categories: ["Brownies", "Desserts"],
    occasions: ["Kids Special"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },

  // ==========================================
  // 5. GIFTING & FESTIVE HAMPERS (7 Products)
  // ==========================================
  {
    id: "premium-luxury-hamper",
    name: "Premium Luxury Gift Hamper",
    description: "Extravagant premium wicker hamper loaded with handmade praline chocolates, cookies, and a red velvet jar.",
    price: 2499,
    categories: ["Hampers"],
    occasions: ["Festival", "Anniversary"],
    flavors: ["Mixed"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1549462980-6a03f721ff03?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isBestseller: true
  },
  {
    id: "bakers-special-box",
    name: "Bakers special Breakfast Box",
    description: "Gourmet box containing 2 chocolate croissants, 2 seed buns and our signature sourdough loaf.",
    price: 899,
    categories: ["Hampers"],
    occasions: ["Festival"],
    flavors: ["Mixed"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isNew: true
  },
  {
    id: "gold-truffle-basket",
    name: "Gold Truffle Festive Basket",
    description: "Elegantly wrapped gold basket featuring 12 customized truffles, cookies, and floral sprigs.",
    price: 1899,
    categories: ["Hampers"],
    occasions: ["Festival"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1513220556108-8e6d3f2ef1d7?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isBestseller: false
  },
  {
    id: "birthday-surprise-casket",
    name: "Bespoke Birthday Surprise Casket",
    description: "An elegant black box holding a custom Bento mini cake, 2 customized chocolate popcakes and beautiful fairy lights.",
    price: 3200,
    categories: ["Hampers"],
    occasions: ["Birthday", "Anniversary"],
    flavors: ["Mixed"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1512909006721-3d6018887383?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true
  },
  {
    id: "high-tea-scone-basket",
    name: "High-Tea Scone & Cookie Basket",
    description: "Elegantly packaged wooden gift basket containing 4 sweet English scones, fresh strawberry jam jar, and 6 assorted almond cookies.",
    price: 1150,
    categories: ["Hampers"],
    occasions: ["Festival", "Anniversary"],
    flavors: ["Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1512200389-dd4cfbd03dd0?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },
  {
    id: "sweet-celebration-assorted-box",
    name: "Sweet Celebration Assorted Cookie Tray",
    description: "A gorgeous luxury gift box wrapped with gold ribbon containing 18 handmade double-chocolate & white almond cookies.",
    price: 799,
    categories: ["Hampers"],
    occasions: ["Festival", "Birthday"],
    flavors: ["Chocolate", "Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1558961309-dbdf03b33fc9?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isBestseller: true
  },
  {
    id: "chocolate-lovers-grand-hamper",
    name: "Chocolate Lover's Grand Hamper",
    description: "The ultimate cocoa dream containing gourmet dark chocolate cookies, 2 chocolate jar cakes, 6 truffle squares, and hot cocoa spoon.",
    price: 1999,
    categories: ["Hampers"],
    occasions: ["Festival", "Anniversary"],
    flavors: ["Chocolate"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1575510629813-fa6bb71e06e3?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },

  // ==========================================
  // 6. ARTISANAL FRESH BREADS (6 Products)
  // ==========================================
  {
    id: "sourdough-boule-classic",
    name: "Sourdough Boule Classic",
    description: "Slow-fermented classic French sourdough boule with thick crunchy crust and airy center.",
    price: 220,
    categories: ["Breads"],
    occasions: ["All"],
    flavors: ["Mixed"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },
  {
    id: "multiseed-loaf",
    name: "Buttery Multi-seed Loaf",
    description: "Slightly sweet premium loaf enriched with sunflower, pumpkin, and brown sesame seeds.",
    price: 180,
    categories: ["Breads"],
    occasions: ["All"],
    flavors: ["Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1589415490074-9f7626d30e7f?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },
  {
    id: "french-baguette-crisp",
    name: "Traditional French Baguette Pair",
    description: "Crispy long crust baguette rolls prepared with real active sourdough cultures, ideal for custom garlic toasts.",
    price: 160,
    categories: ["Breads"],
    occasions: ["All"],
    flavors: ["Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1585478259715-876acc5be8eb?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isNew: true
  },
  {
    id: "herbed-garlic-butter-bread",
    name: "Gourmet Garlic Butter Herbed Loaf",
    description: "Pull-apart buttery bread loaded inside and out with baked minced garlic, organic rosemary and fresh garden herbs.",
    price: 199,
    categories: ["Breads"],
    occasions: ["All"],
    flavors: ["Mixed"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1621932953986-15fcfec81908?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false,
    isBestseller: true
  },
  {
    id: "olive-focaccia-slice",
    name: "Italian Black Olive Focaccia",
    description: "Thick oil-rich yeast bread decorated with salty kalamata olives, rosemary springs, and crystal sea salt granules.",
    price: 210,
    categories: ["Breads"],
    occasions: ["All"],
    flavors: ["Mixed"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  },
  {
    id: "brioche-burger-buns",
    name: "Buttery Brioche Buns (4 Pcs)",
    description: "Rich, golden buns baked with pure pasture butter and sugar cane extract, glazed and sprinkled with sesame seeds.",
    price: 140,
    categories: ["Breads"],
    occasions: ["All"],
    flavors: ["Vanilla"],
    dietary: ["Eggless"],
    images: ["https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800"],
    stockStatus: "in-stock",
    isCustomizable: false
  }
];

function getSuperheroCakes(): Product[] {
  const list: { name: string; desc: string; flavor: string; img: string; price: number }[] = [
    // 1-20 Explicitly requested:
    { name: "Iron Man Cake", desc: "Premium chocolate truffle cake with an edible gold-and-red armored plate design and glowing Arc Reactor frosting.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1574085733277-851d9d856a3a?auto=format&fit=crop&q=80&w=800", price: 1899 },
    { name: "Captain America Cake", desc: "A majestic blueberry sponge cake featuring the iconic stars-and-stripes Vibranium Shield topper.", flavor: "Blueberry", img: "https://images.unsplash.com/photo-1535141123063-02f50b93a303?auto=format&fit=crop&q=80&w=800", price: 1799 },
    { name: "Batman Cake", desc: "Dark-themed Belgian dark chocolate cake with Gotham's iconic bat signal yellow badge and chocolate skyline.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1516685018646-549198525c1b?auto=format&fit=crop&q=80&w=800", price: 1999 },
    { name: "Superman Cake", desc: "Royal blue and red cake layered with vanilla cream, complete with the famous House of El 'S' crest.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1614707267537-b85acf00c4b8?auto=format&fit=crop&q=80&w=800", price: 1750 },
    { name: "Spider-Man Cake", desc: "Spun sugar-web red velvet cake featuring hand-piped black webs and Spider-Man's striking white eyes.", flavor: "Red Velvet", img: "https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&q=80&w=800", price: 1850 },
    { name: "Hulk Cake", desc: "Furious gamma-green pistachio and cardamon cake styled with a crashing chocolate fist and purple sprinkles.", flavor: "Mixed", img: "https://images.unsplash.com/photo-1512414589043-f11bfa6e54b8?auto=format&fit=crop&q=80&w=800", price: 1699 },
    { name: "Thor Cake", desc: "Nordic chocolate-fudge cake crowned with a solid, realistic marshmallow Mjolnir Hammer and blue lightning.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&q=80&w=800", price: 2100 },
    { name: "Black Widow Cake", desc: "Sleek black cocoa cake with a vibrant crimson hourglass emblem and hand-drawn dark chocolate spiders.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&q=80&w=800", price: 1899 },
    { name: "Black Panther Cake", desc: "Wakanda-inspired deep purple blackberry and chocolate ganache cake detailed with silver warrior necklace beads.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80&w=800", price: 2200 },
    { name: "Wonder Woman Cake", desc: "Royal golden-tiara star-spangled red velvet cake with gold lasso details and blue bottom stars.", flavor: "Red Velvet", img: "https://images.unsplash.com/photo-1513135065346-a098a63a71ee?auto=format&fit=crop&q=80&w=800", price: 1950 },
    { name: "The Flash Cake", desc: "Vibrant yellow-and-red strawberry-jam cake decorated with an electric lightning bolt and super-speed trails.", flavor: "Strawberry", img: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&q=80&w=800", price: 1799 },
    { name: "Doctor Strange Cake", desc: "Eye of Agamotto mystical orange-spice cake with cosmic portal rings and a sugar Cloak of Levitation.", flavor: "Mixed", img: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=800", price: 2400 },
    { name: "Aquaman Cake", desc: "Deep sea green-and-gold vanilla sponge cake featuring detailed fish-scale frosting and a golden trident.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1511018556340-d16986a1c194?auto=format&fit=crop&q=80&w=800", price: 1899 },
    { name: "Wolverine Cake", desc: "X-Men yellow and blue butterscotch cake sliced with triple metallic-silver chocolate adamantium claws.", flavor: "Butterscotch", img: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&q=80&w=800", price: 1850 },
    { name: "Deadpool Cake", desc: "Cheeky and hilarious red-and-black velvet cake with dual chocolate swords and witty edible messages.", flavor: "Red Velvet", img: "https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&q=80&w=800", price: 1999 },
    { name: "Thanos Cake", desc: "Imperial gold and purple blueberry cake decorated with six glowing candy Infinity Stones on the gauntlet.", flavor: "Blueberry", img: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80&w=800", price: 2500 },
    { name: "Green Lantern Cake", desc: "Pistachio-mint cake displaying the glowing emerald Green Lantern insignia with cosmic power-ring sparkles.", flavor: "Mixed", img: "https://images.unsplash.com/photo-1512414589043-f11bfa6e54b8?auto=format&fit=crop&q=80&w=800", price: 1750 },
    { name: "Daredevil Cake", desc: "Hell's Kitchen fiery-red cinnamon chocolate cake featuring devil horns and double chocolate billy clubs.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800", price: 1800 },
    { name: "Hawkeye Cake", desc: "Deep violet blueberry and cream cake with hand-painted archer arrows and a sweet purple bow topper.", flavor: "Blueberry", img: "https://images.unsplash.com/photo-1535141123063-02f50b93a303?auto=format&fit=crop&q=80&w=800", price: 1699 },
    { name: "Ant-Man Cake", desc: "Microscopic detailed red vanilla cake that looks small but is packed with giant quantum honey flavors.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&q=80&w=800", price: 1650 },

    // 21-70 50 additional cakes:
    { name: "Loki Mischief Cake", desc: "Green and gold butterscotch cake featuring Loki's famous curved golden horns and trickster emerald dust.", flavor: "Butterscotch", img: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&q=80&w=800", price: 1950 },
    { name: "Vision Vibranium Cake", desc: "Turquoise and maroon cake featuring the bright golden Mind Stone resting on Vision's forehead plate.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1511018556340-d16986a1c194?auto=format&fit=crop&q=80&w=800", price: 1890 },
    { name: "Scarlet Witch Chaos Cake", desc: "Crimson red velvet cake wrapped in dark energy crown stencils and cherry chaos magic drizzle.", flavor: "Red Velvet", img: "https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&q=80&w=800", price: 2150 },
    { name: "Winter Soldier Cake", desc: "Chrome-silver brushed chocolate cake with a bright red star on a dark chocolate cybernetic sleeve.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800", price: 1800 },
    { name: "Falcon Wings Cake", desc: "Patriotic silver, red and blue cake with majestic sugar wing panels spreading from the center.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1614707267537-b85acf00c4b8?auto=format&fit=crop&q=80&w=800", price: 1900 },
    { name: "Shang-Chi Ten Rings Cake", desc: "Golden honey sponge layered with ten interlocking chocolate rings resting on ancient dragon scales.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1512414589043-f11bfa6e54b8?auto=format&fit=crop&q=80&w=800", price: 2100 },
    { name: "Ms. Marvel Cosmic Cake", desc: "Vibrant pink-and-blue velvet cake decorated with a bright golden lightning sash and cosmic star dust.", flavor: "Red Velvet", img: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800", price: 1750 },
    { name: "Moon Knight Crescent Cake", desc: "All-white cream and vanilla cake styled with a silver crescent moon and ancient Egyptian hieroglyphs.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&q=80&w=800", price: 1980 },
    { name: "She-Hulk Gamma Cake", desc: "Vibrant neon-green lime and vanilla cake decorated with purple court files and heavy barbell sugar work.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&q=80&w=800", price: 1750 },
    { name: "Miles Morales Neon Cake", desc: "Glow-in-the-dark themed black and neon-red graffiti cake with spider logos and spray-paint effects.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&q=80&w=800", price: 1890 },
    { name: "Gwen Stacy Spider Cake", desc: "Stunning pink, white, and teal hooded cake with beautiful web patterns and ballet dancer ribbon details.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1614707267537-b85acf00c4b8?auto=format&fit=crop&q=80&w=800", price: 1850 },
    { name: "Green Goblin Glider Cake", desc: "Salty-sweet lime and dark chocolate cake styled with a miniature sugar glider and orange pumpkin bombs.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&q=80&w=800", price: 1999 },
    { name: "Carnage Symbiote Cake", desc: "Wildly decorated red velvet cake with creeping black and crimson chocolate tendrils and terrifying teeth.", flavor: "Red Velvet", img: "https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&q=80&w=800", price: 2200 },
    { name: "Venom Dark Host Cake", desc: "Jet black dark chocolate ganache cake bursting with a giant white-fanged symbiote smile and pink tongue.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800", price: 2200 },
    { name: "Joker Mad Jester Cake", desc: "Bright purple and toxic green cake with Joker's iconic red 'HA HA HA' smiles and card toppers.", flavor: "Mixed", img: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=800", price: 1999 },
    { name: "Catwoman Midnight Cake", desc: "Sleek black-leather finish vanilla cake decorated with shiny silver whip work and cute cat ear contours.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1527489377706-5bf97e608852?auto=format&fit=crop&q=80&w=800", price: 1850 },
    { name: "Harley Quinn Puddin Cake", desc: "Split pink-and-blue candy cake featuring Harley's diamonds, comic mallet, and 'Puddin' written in gold.", flavor: "Strawberry", img: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&q=80&w=800", price: 1950 },
    { name: "Riddler Mystery Cake", desc: "Mysterious green cake covered in dozens of black question marks and a dark chocolate question staff.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1511018556340-d16986a1c194?auto=format&fit=crop&q=80&w=800", price: 1750 },
    { name: "Bane Venom Serum Cake", desc: "Heavy industrial cake styled with wrestling straps and glowing green toxic serum tubes.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&q=80&w=800", price: 1990 },
    { name: "Robin Boy Wonder Cake", desc: "Classic red, green, and yellow cake with the robin bird shield and dual golden utility belt pockets.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1614707267537-b85acf00c4b8?auto=format&fit=crop&q=80&w=800", price: 1699 },
    { name: "Nightwing Blue Crest Cake", desc: "High-contrast midnight-black cake featuring the bright electric-blue bird silhouette across the tier.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1516685018646-549198525c1b?auto=format&fit=crop&q=80&w=800", price: 1850 },
    { name: "Batgirl Gotham Cake", desc: "Stylish purple and yellow cake decorated with bat-logo crests and shiny yellow utility belt swirls.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1535141123063-02f50b93a303?auto=format&fit=crop&q=80&w=800", price: 1799 },
    { name: "Supergirl House of El Cake", desc: "Bright sky blue cake decorated with a dynamic red cape wrap and gold star-spangled trim.", flavor: "Strawberry", img: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&q=80&w=800", price: 1800 },
    { name: "Shazam Thunder Cake", desc: "Bright red cake showing off a giant golden lightning bolt that appears to strike from clouds of sugar.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&q=80&w=800", price: 1750 },
    { name: "Black Adam Kahndaq Cake", desc: "Intense black and gold lightning cake displaying the ancient hieroglyphs of Kahndaq in gold leaf.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1527489377706-5bf97e608852?auto=format&fit=crop&q=80&w=800", price: 2100 },
    { name: "Cyborg Tech Core Cake", desc: "Futuristic silver-brushed vanilla cake featuring a glowing red candy eye core and circuit board traces.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&q=80&w=800", price: 1950 },
    { name: "Beast Boy Shifter Cake", desc: "Playful green cake displaying funny animal silhouettes and a chocolate gaming controller.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1512414589043-f11bfa6e54b8?auto=format&fit=crop&q=80&w=800", price: 1700 },
    { name: "Raven Azarath Cake", desc: "Mystical deep purple and black layered dark forest cake with floating chocolate ravens and dark swirls.", flavor: "Blueberry", img: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80&w=800", price: 2000 },
    { name: "Starfire Tamaranean Cake", desc: "Beautiful pink and purple cake decorated with glowing starfire energy blasts and orange stars.", flavor: "Strawberry", img: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&q=80&w=800", price: 1850 },
    { name: "Professor X Mind Cake", desc: "Sleek blue metallic cake detailed with the silver Cerebro helm design and circular mind-wave patterns.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1511018556340-d16986a1c194?auto=format&fit=crop&q=80&w=800", price: 1900 },
    { name: "Magneto Metal Cake", desc: "Stunning maroon and purple cake with a prominent metallic helmet and twisted copper wire decorations.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&q=80&w=800", price: 2200 },
    { name: "Cyclops Optic Blast Cake", desc: "Deep blue cake highlighted by a giant gold visor projecting an intense red laser stream of sugar.", flavor: "Blueberry", img: "https://images.unsplash.com/photo-1535141123063-02f50b93a303?auto=format&fit=crop&q=80&w=800", price: 1750 },
    { name: "Jean Grey Phoenix Cake", desc: "Spectacular orange, yellow and red cake painted with the flaming wings of the Cosmic Phoenix.", flavor: "Red Velvet", img: "https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&q=80&w=800", price: 2350 },
    { name: "Storm Goddess Cake", desc: "Dark stormy grey cake topped with towering sugar clouds and crackling white chocolate lightning bolts.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&q=80&w=800", price: 2100 },
    { name: "Wolverine Berserker Cake", desc: "X-Men yellow-masked cake showing Wolverine's angry expression and chocolate slash marks.", flavor: "Butterscotch", img: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&q=80&w=800", price: 1890 },
    { name: "Rogue Absorbing Cake", desc: "Charming green and white cake decorated with double chocolate locks and power glove toppers.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1511018556340-d16986a1c194?auto=format&fit=crop&q=80&w=800", price: 1780 },
    { name: "Gambit Kinetic Cake", desc: "Cool pink and brown cake with exploding sugar playing cards glowing with bright pink energy waves.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&q=80&w=800", price: 2000 },
    { name: "Baby Groot Pot Cake", desc: "Cutest cake designed as Baby Groot in a flowerpot with realistic edible bark and green leaves.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800", price: 1999 },
    { name: "Star-Lord Mix Cake", desc: "Retro cassette tape cake showing 'Awesome Mix Vol. 1' with chocolate headphones and stellar stars.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&q=80&w=800", price: 1850 },
    { name: "Rocket Raccoon Cake", desc: "Funny raccoon cake holding a gigantic plasma cannon made of pure fudge and dark chocolate.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&q=80&w=800", price: 1890 },
    { name: "Gamora Zen-Whoberi Cake", desc: "Sleek green and silver cake with elegant dual sword crossings and floral galaxy accents.", flavor: "Strawberry", img: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800", price: 1800 },
    { name: "Drax The Destroyer Cake", desc: "Durable silver and red-tattooed chocolate cake complete with edible twin daggers and starry background.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800", price: 1850 },
    { name: "Nebula Cybernetic Cake", desc: "Icy blue and metallic silver cake representing the cybernetic warrior of the galaxy with star gems.", flavor: "Blueberry", img: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80&w=800", price: 1900 },
    { name: "Nick Fury S.H.I.E.L.D. Cake", desc: "A sleek black trenchcoat cake with the prominent S.H.I.E.L.D. circular seal and chocolate eye-patch.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1527489377706-5bf97e608852?auto=format&fit=crop&q=80&w=800", price: 1750 },
    { name: "Captain Marvel Binary Cake", desc: "Majestic blue, gold, and red star-crest cake surrounded by glowing orange cosmic energy sugar clouds.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1511018556340-d16986a1c194?auto=format&fit=crop&q=80&w=800", price: 2150 },
    { name: "Ghost Rider Hellfire Cake", desc: "Fierce chocolate cake featuring a fiery flaming sugar skull with blazing chains and sweet ash dust.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1574085733277-851d9d856a3a?auto=format&fit=crop&q=80&w=800", price: 2300 },
    { name: "Punisher Skull Crest Cake", desc: "Grim black cake with the iconic giant white skull emblem stenciled precisely onto charcoal icing.", flavor: "Chocolate", img: "https://images.unsplash.com/photo-1527489377706-5bf97e608852?auto=format&fit=crop&q=80&w=800", price: 1790 },
    { name: "Silver Surfer Cosmic Cake", desc: "Stunning chrome-glazed cake featuring a chocolate surfboard surfing across cosmic purple galaxies.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1516685018646-549198525c1b?auto=format&fit=crop&q=80&w=800", price: 2000 },
    { name: "Galactus Devourer Cake", desc: "A colossal purple-helmeted double-tiered cake shown eating a sweet tiny sugar planet Earth.", flavor: "Blueberry", img: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80&w=800", price: 2600 },
    { name: "Stan Lee Tribute Cake", desc: "Sweetest legacy cake displaying cartoon comics, black glasses, and the legendary signature 'Excelsior!'.", flavor: "Vanilla", img: "https://images.unsplash.com/photo-1614707267537-b85acf00c4b8?auto=format&fit=crop&q=80&w=800", price: 1926 }
  ];

  return list.map((item) => {
    const cleanId = "superhero-" + item.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
    return {
      id: cleanId,
      name: item.name,
      description: item.desc,
      price: item.price,
      categories: ["Cakes"], // Classified under "Cakes"
      occasions: ["Birthday", "Kids Special"], // Classified under Birthday and Kids Special
      flavors: [item.flavor],
      dietary: ["Eggless"],
      images: [item.img],
      stockStatus: "in-stock",
      isCustomizable: true,
      isBestseller: false,
      weights: [1, 1.5, 2, 3]
    } as Product;
  });
}

export const FALLBACK_PRODUCTS: Product[] = BASE_PRODUCTS.concat(getSuperheroCakes());

