import { Product } from '../types';

export const PREMIUM_PRODUCTS_POOL: Product[] = [
  {
    id: "prod-1",
    name: "Golden Empress Truffle Drip Cake",
    description: "Layers of pristine Belgian dark chocolate fudge sponge, 24k edible gold leaf gilding, artisanal hand-crafted macarons, and vanilla buttercream rosettes.",
    price: 1899,
    categories: ["Cakes", "Premium Collection"],
    occasions: ["Birthday", "Anniversary"],
    flavors: ["Chocolate"],
    images: ["https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80", "https://images.unsplash.com/photo-1586985289688-ca9cf4993ec0?w=800&q=80", "https://images.unsplash.com/photo-1542826438-bd32f43d626f?w=800&q=80"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    isNew: false,
    weights: [0.5, 1.0, 2.0],
    dietary: ["Eggless", "Gluten Free"],
    rating: 4.9,
    reviewsCount: 342,
  },
  {
    id: "prod-2",
    name: "Wild Strawberry Shimmer Tier Cake",
    description: "Multi-tiered masterpiece filled with signature whipped double cream, fresh organic strawberry coulis, delicate pink meringue wafers, and cosmic sparkle dust.",
    price: 2450,
    categories: ["Cakes", "Premium Collection"],
    occasions: ["Anniversary", "Wedding"],
    flavors: ["Strawberry"],
    images: ["https://images.unsplash.com/photo-1535141192574-5d4897c13636?w=800&q=80", "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=800&q=80"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    isNew: true,
    weights: [1.0, 2.0, 3.0],
    dietary: ["Eggless", "Vegan"],
    rating: 5.0,
    reviewsCount: 198,
  },
  {
    id: "prod-3",
    name: "Belgian Velvet Eclipse Cake",
    description: "Rich traditional buttermilk red velvet sponge paired with signature Madagascan cream cheese frosting, hand-crushed crystal chocolate crumbs, and garden-fresh red roses.",
    price: 1299,
    categories: ["Cakes", "Regular Cakes"],
    occasions: ["Birthday", "Anniversary"],
    flavors: ["Red Velvet"],
    images: ["https://images.unsplash.com/photo-1586985289688-ca9cf4993ec0?w=800&q=80", "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    isNew: false,
    weights: [0.5, 1.0, 2.0],
    dietary: ["Eggless"],
    rating: 4.8,
    reviewsCount: 512,
  },
  {
    id: "prod-4",
    name: "Gourmet Pistachio & Blueberry Ombre",
    description: "Ethereal pistachio crumb cake layered with wild blueberry curd, elegant lavender frosting swirls, and fresh hand-plucked organic berries.",
    price: 1650,
    categories: ["Cakes", "Bento & Mini Cakes"],
    occasions: ["Festival", "Birthday"],
    flavors: ["Blueberry"],
    images: ["https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=800&q=80"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    isNew: false,
    weights: [0.5, 1.0],
    dietary: ["Eggless", "Sugar Free"],
    rating: 4.7,
    reviewsCount: 88,
  },
  {
    id: "prod-5",
    name: "Dark Forest Truffle Drip Cake",
    description: "Delicate cocoa sponge drenched in premium cherry syrup, layered with sweet black cherries, clouds of fresh chantilly cream, and custom chocolate shards.",
    price: 999,
    categories: ["Cakes", "Regular Cakes"],
    occasions: ["Birthday", "Festival"],
    flavors: ["Chocolate"],
    images: ["https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&q=80"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    isNew: false,
    weights: [0.5, 1.0, 2.0],
    dietary: ["With Egg", "Vegan"],
    rating: 4.6,
    reviewsCount: 147,
  },
  {
    id: "prod-6",
    name: "Parisian Rose Gold Macaron Tower",
    description: "Stately arrangement of crispy hand-baked rose-infused macarons filled with white chocolate ganache, nestled atop a vanilla cloud cake.",
    price: 2999,
    categories: ["Cakes", "Premium Collection"],
    occasions: ["Anniversary", "Wedding"],
    flavors: ["Vanilla"],
    images: ["https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=800&q=80"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    isNew: true,
    weights: [1.0, 2.0, 3.0],
    dietary: ["Eggless"],
    rating: 4.9,
    reviewsCount: 110,
  },
  {
    id: "prod-7",
    name: "Madagascan Butterscotch Ribbon Cake",
    description: "Airy vanilla sponge coated in caramelized praline butterscotch cream, cascading rich caramel butter sauce, and roasted almond flakes.",
    price: 899,
    categories: ["Cakes", "Regular Cakes"],
    occasions: ["Birthday", "Kids"],
    flavors: ["Butterscotch"],
    images: ["https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: false,
    isNew: false,
    weights: [0.5, 1.0, 2.0],
    dietary: ["Eggless"],
    rating: 4.5,
    reviewsCount: 220,
  },
  {
    id: "prod-8",
    name: "Saffron Royal Cardamom Heritage Cake",
    description: "An exotic fusion featuring saffron milk cardamom syrup, soft pistachio sponge, garnished with silver foil (Chandi Vark) and pistachios.",
    price: 1599,
    categories: ["Cakes", "Premium Collection"],
    occasions: ["Festival", "Anniversary"],
    flavors: ["Vanilla"],
    images: ["https://images.unsplash.com/photo-1519340330284-26a9e7f1e5d3?w=800&q=80"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    isNew: false,
    weights: [0.5, 1.0, 2.0],
    dietary: ["Eggless", "Sugar Free"],
    rating: 4.9,
    reviewsCount: 132,
  },
  {
    id: "prod-9",
    name: "Celestial Rainbow Pinata Mystery",
    description: "Stunning solid white-chocolate pinata dome encasing a secret cache of colorful premium gems, sweet cookies, and customizable heart notes inside.",
    price: 1750,
    categories: ["Cakes", "Pinata Cakes"],
    occasions: ["Kids", "Birthday"],
    flavors: ["Chocolate"],
    images: ["https://images.unsplash.com/photo-1557925923-cd4648e21187?w=800&q=80"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    isNew: true,
    weights: [1.0],
    dietary: ["Eggless"],
    rating: 4.9,
    reviewsCount: 75,
  },
  {
    id: "prod-10",
    name: "Ferrero Royal Praline Drip",
    description: "Indulgent Nutella cream layers, crunch hazelnuts, chocolate sponge, crowned with premium Ferrero Rocher globes and shiny fudge spirals.",
    price: 1999,
    categories: ["Cakes", "Premium Collection"],
    occasions: ["Anniversary", "Birthday"],
    flavors: ["Ferrero"],
    images: ["https://images.unsplash.com/photo-1542826438-bd32f43d626f?w=800&q=80"],
    stockStatus: "in-stock",
    isCustomizable: true,
    isBestseller: true,
    isNew: false,
    weights: [1.0, 2.0],
    dietary: ["Eggless"],
    rating: 5.0,
    reviewsCount: 418,
  },
  {
    id: "prod-11",
    name: "Fudge Brownie Cupcake Dream",
    description: "Rich, dense chocolate fudge cupcake topped with premium cocoa mousse and chocolate sprinkles.",
    price: 249,
    categories: ["Cupcakes"],
    occasions: ["Kids", "Birthday"],
    flavors: ["Chocolate"],
    images: ["https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&q=80"],
    stockStatus: "in-stock",
    isCustomizable: false,
    weights: [0.1],
    dietary: ["Eggless"],
    rating: 4.8,
    reviewsCount: 92,
  },
  {
    id: "prod-12",
    name: "Chilled Mango Panna Cotta",
    description: "Silky-smooth panna cotta layer sweetened with natural Alphonso mango pulp and fresh mint toppers.",
    price: 450,
    categories: ["Desserts"],
    occasions: ["Festival", "Anniversary"],
    flavors: ["Mango"],
    images: ["https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80"],
    stockStatus: "in-stock",
    isCustomizable: false,
    weights: [0.2],
    dietary: ["Eggless", "Gluten Free"],
    rating: 4.7,
    reviewsCount: 64,
  },
  {
    id: "prod-13",
    name: "Royal Celebration Gift Hamper",
    description: "A gorgeous luxury gift casket including a mini chocolate drip cake, 6 macaron assorted pieces, and a bouquet of red roses.",
    price: 3499,
    categories: ["Gift Hampers"],
    occasions: ["Anniversary", "Wedding", "Festival"],
    flavors: ["Chocolate", "Strawberry"],
    images: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&q=80"],
    stockStatus: "in-stock",
    isCustomizable: true,
    weights: [2.5],
    dietary: ["Eggless"],
    rating: 5.0,
    reviewsCount: 154,
  }
];

export const PREMIUM_ACCESSORIES = [
  { id: "acc-1", name: "Sparkling Starry Candles (Set of 6)", price: 49, image: "https://images.unsplash.com/photo-1541336032412-2048a678540d?w=400&q=80" },
  { id: "acc-2", name: "Premium Embossed Greeting Card", price: 99, image: "https://images.unsplash.com/photo-1512909006721-3d6018887383?w=400&q=80" },
  { id: "acc-3", name: "Fresh Royal Velvet Red Roses (Bunch)", price: 299, image: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=400&q=80" },
  { id: "acc-4", name: "Signature Rich Chocolate Bouquet", price: 499, image: "https://images.unsplash.com/photo-1511381939415-e44015466834?w=400&q=80" },
  { id: "acc-5", name: "Helium Celebration Balloons (Bunch of 5)", price: 149, image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400&q=80" },
  { id: "acc-6", name: "Luxury Golden Wrapping Gift Box", price: 199, image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=400&q=80" }
];

export const getProductSpecs = (prod: Product) => {
  const caloriesMap: Record<string, number> = {
    "prod-1": 420, "prod-2": 380, "prod-3": 450, "prod-4": 310, "prod-5": 400,
    "prod-6": 480, "prod-7": 390, "prod-8": 360, "prod-9": 410, "prod-10": 460,
    "prod-11": 180, "prod-12": 220, "prod-13": 850
  };
  const shelfLifeMap: Record<string, string> = {
    "prod-1": "48 Hours (Refrigerated)", 
    "prod-2": "24 Hours (Fresh Berry Content)", 
    "prod-3": "72 Hours (Refrigerated)", 
    "prod-4": "36 Hours (Refrigerated)",
    "prod-5": "48 Hours (Refrigerated)", 
    "prod-6": "48 Hours (Cool Dry Storage)", 
    "prod-7": "72 Hours (Refrigerated)", 
    "prod-8": "48 Hours (Refrigerated)",
    "prod-9": "72 Hours (Dry Storage)", 
    "prod-10": "48 Hours (Refrigerated)", 
    "prod-11": "24 Hours (Ambient Temp)", 
    "prod-12": "24 Hours (Fully Chilled)",
    "prod-13": "48 Hours (Ambient Temp)"
  };
  const ingredientsMap: Record<string, string[]> = {
    "prod-1": ["72% Belgian chocolate fudge", "24K Edible gold leaf", "Fresh raspberry infusion", "Madagascar cocoa"],
    "prod-2": ["Organic wild strawberries", "Coconut double whip cream", "Oat-milk sponge base", "Glitter sugar sprinkles"],
    "prod-3": ["Premium cocoa crumble", "Vanilla cheese cream frosting", "Beetroot natural extracts", "Organic buttermilk"],
    "prod-4": ["Crushed Turkish pistachios", "Wild blueberry fruit purée", "Stevia leaf sweetener", "Almond milk batter"],
    "prod-5": ["Glazed dark sweet cherries", "Belgian chocolate ganache", "Dairy-free whipping cream", "Cocoa shavings"],
    "prod-6": ["French macaron shells", "Rose water extract", "White cocoa paste ganache", "Bourbon vanilla pods"],
    "prod-7": ["Caramelized butterscotch praline", "Golden brown sugar", "Soft vanilla sponge", "Cracked almond slivers"],
    "prod-8": ["Kashmiri saffron strands", "Cardamom pod essence", "Green pistachio meal", "Pure silver foil gilding"],
    "prod-9": ["White cocoa butter pinata dome", "Secret gems candy center", "Baked cookie crumbles", "Heart-shaped custom message"],
    "prod-10": ["Nutella cocoa spread", "Toasted Piedmont hazelnuts", "Original Ferrero Rocher globes", "Fudge syrup drizzle"],
    "prod-11": ["Dense fudge cocoa", "Egg-free pastry flour", "Pure chocolate chips", "Sea salt touch"],
    "prod-12": ["Alphonso mango pulp", "Organic grass-fed dairy cream", "Fresh organic mint leaves", "Agar-agar organic binder"],
    "prod-13": ["Premium chocolate truffles box", "Assorted French macarons", "Cold press fruit jam jar", "Scented candles packet"]
  };
  const prepTimeMap: Record<string, string> = {
    "prod-1": "6h (Designer)", "prod-2": "4h (Standard)", "prod-3": "2h (Express)", "prod-4": "4h (Standard)",
    "prod-5": "2h (Express)", "prod-6": "12h (Designer)", "prod-7": "3h (Standard)", "prod-8": "4h (Standard)",
    "prod-9": "5h (Standard)", "prod-10": "6h (Designer)", "prod-11": "1h (Express)", "prod-12": "1h (Express)",
    "prod-13": "4h (Standard)"
  };

  const id = prod.id;
  return {
    calories: caloriesMap[id] || 380,
    shelfLife: shelfLifeMap[id] || "48 Hours",
    ingredients: ingredientsMap[id] || ["Premium pastry flour", "Organic sugar", "Whipped dairy cream", "Vanilla bean paste"],
    prepTime: prepTimeMap[id] || "Standard (3h)"
  };
};
